### ISSUE TITLE
נגישות BlogPosts בעמוד הראשי - הלינק מחולק לשניים

### ISSUE THREAD

**Issue by drorsnir** [kolzchut/mediawiki-extensions-BlogPosts#1]
לחלק הראשון (התמונה) אין טקסט. הדרך הנכונה היא לעטוף את התמונה והטקסט ביחד!

**Comment by drorsnir** [comment]
נראה שכבר תיקנתי את זה.

**Comment by dewbjorn** [comment]
בדיוק קיבלתי נוטיפיקציה במייל על האישיו הזה וזה הזכיר לי את הכיף שהיה כאן לפני כמה שנים :)

ד"ש חם @drorsnir

**Comment by dewbjorn** [comment]
(טל קורן מאינטרג'ט 😉)

**Comment by drorsnir** [comment]
צחוקים! ד"ש בחזרה :-)
